### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by EricRibeiro** [autifyhq/autify-circleci-orb-cli#1]
Hello Autify team 👋

I am from the @circleci Community and Partner Engineering team, here to help with a review for the CircleCI orb partnership. I have an action item below for you:

- Double quote variables

The variable at the line [5](https://github.com/autifyhq/autify-circleci-orb-cli/blob/main/src/scripts/install.bash#L5) should be double-quoted to comply with [SC2086](https://www.shellcheck.net/wiki/SC2086).

---
Feel free to ask me any questions, and please include me as a reviewer in the PR with the changes. Thank you!

**Comment by riywo** [comment]
@EricRibeiro Thank you for such a deep review! I fixed the violation and released v1.0.1.
